[build]
  base = "client/"
  publish = "build/"
  command = "npm run build"

[build.environment]
  REACT_APP_API_URL = "https://trading-journal-web-app.onrender.com/api/v1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
