services:
  # Backend API service
  - type: web
    name: trading-journal-api
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: trading_journal_secure_secret_key_2025
      - key: JWT_EXPIRE
        value: 24h
      - key: MONGO_URI
        value: mongodb+srv://lollyethan25:X%3DS%5DqZiQYWvOn%3A%2FT@cluster0.7tdlzki.mongodb.net/trading_journal?retryWrites=true&w=majority&appName=Cluster0
      - key: LOG_LEVEL
        value: info
      - key: CLIENT_URL
        fromService:
          name: trading-journal-client
          type: web
          envVarKey: RENDER_EXTERNAL_URL
    healthCheckPath: /api/v1/health

  # Frontend static site
  - type: static
    name: trading-journal-client
    plan: free
    buildCommand: cd client && npm install && npm run build
    publishPath: client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: trading-journal-api
          type: web
          envVarKey: RENDER_EXTERNAL_URL
        suffix: /api/v1
